apiVersion: v1
kind: Pod
metadata:
  name: docker-stats
spec:
  containers:
  - name: docker-stats
    image: docker.io/falkonry/docker-stats:latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: docker
      mountPath: /var/run/docker.sock
      readOnly: true
  volumes:
  - name: docker
    hostPath:
      path: /var/run/docker.sock
